<h1 style="text-align: center;">Individual Assignment 1 - Part 1</h1>
<h3 style="text-align: center;">Case Studies for Data Science - semester 2 2026</h3> 
<h4 style="text-align: center;"> Rose Munro s4054011 </h4>

In [1]:
#TODO: Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import sklearn TODO: select models

---

#### Load Australian Bureau of Statistics Data
##### Socio-Economic Indexes for Australia (SEIFA), 2021

In [2]:
#TODO: load data sets (2)
#Read ABS SEIFA 2021 
SEIFA21_df = pd.read_excel("data/Postal Area, Indexes, SEIFA 2021.xlsx",
                         sheet_name = "Table 1",
                         header = 5,
                         dtype={"2021 Postal Area (POA) Code": str})#do not round postcodes, they are indexes not numric
SEIFA21_df.head()

,2021 Postal Area (POA) Code,Score,Decile,Score.1,Decile.1,Score.2,Decile.2,Score.3,Decile.3,Usual Resident Population,Data should be used with caution - area not well represented by SA1s,POA crosses state or territory boundaries
0,0800,1064.349794,9,1084.261433,9,921.395254,1,1089.647675,9.0,7149.0,NaN,NaN
1,0810,1026.802176,7,1036.266842,8,992.867218,5,1047.620794,8.0,34330.0,NaN,NaN
2,0812,981.137162,4,981.720979,6,977.777285,4,978.905626,6.0,18634.0,NaN,NaN
3,0820,1061.250806,9,1075.721877,9,981.896356,4,1076.326539,9.0,19920.0,NaN,NaN
4,0822,601.552207,1,760.604459,1,630.686758,1,885.789899,1.0,25304.0,NaN,NaN

In [3]:
#rename cols ABS SEIFA
SEIFA21_df.columns = [
    "postcode",
    "irsd_score", #Index of Relative Socio-economic Disadvantage
    "irsd_decile",
    "irsad_score", # Index of Relative Socio-economic Advantage and Disadvantage	
    "irsad_decile",
    "ier_score", # Index of Economic Resources	
    "ier_decile",
    "ieo_score", # Index of Education and Occupation
    "ieo_decile",
    "population", # Usual Resident Population
    "caution_flag", # Data should be used with caution - area not well represented by SA1s
    "crosses_state_boundary" # POA crosses state or territory boundaries

]

SEIFA21_df.head(10)

,postcode,irsd_score,irsd_decile,irsad_score,irsad_decile,ier_score,ier_decile,ieo_score,ieo_decile,population,caution_flag,crosses_state_boundary
0,0800,1064.349794,9,1084.261433,9,921.395254,1,1089.647675,9.0,7149.0,NaN,NaN
1,0810,1026.802176,7,1036.266842,8,992.867218,5,1047.620794,8.0,34330.0,NaN,NaN
2,0812,981.137162,4,981.720979,6,977.777285,4,978.905626,6.0,18634.0,NaN,NaN
3,0820,1061.250806,9,1075.721877,9,981.896356,4,1076.326539,9.0,19920.0,NaN,NaN
4,0822,601.552207,1,760.604459,1,630.686758,1,885.789899,1.0,25304.0,NaN,NaN
5,0828,989.319795,5,999.91593,7,975.654307,4,985.144346,6.0,1697.0,NaN,NaN
6,0829,892.688966,1,857.561406,1,873.251436,1,841.989099,1.0,1963.0,NaN,NaN
7,0830,969.591287,4,963.341382,5,956.510726,3,948.909360,4.0,18501.0,NaN,NaN
8,0832,1048.448577,8,1032.478619,8,1025.31097,7,994.016467,7.0,18727.0,NaN,NaN
9,0834,1057.389015,9,1050.617815,8,1077.294216,9,983.332490,6.0,1811.0,NaN,NaN

In [4]:
SEIFA21_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2629 entries, 0 to 2628
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   postcode                2628 non-null   str
 1   irsd_score              2627 non-null   object
 2   irsd_decile             2627 non-null   object
 3   irsad_score             2627 non-null   object
 4   irsad_decile            2627 non-null   object
 5   ier_score               2627 non-null   object
 6   ier_decile              2627 non-null   object
 7   ieo_score               2627 non-null   float64
 8   ieo_decile              2627 non-null   float64
 9   population              2627 non-null   float64
 10  caution_flag            167 non-null    str
 11  crosses_state_boundary  15 non-null     str
dtypes: float64(3), object(6), str(3)
memory usage: 246.6+ KB

---

#### Load Australian Curriculum Assessment and Reporting Authority (ACARA) Data
##### School Profile & School Location, 2025

In [25]:
#ACARA LOCATION
ACARA_location_df = pd.read_excel("data/School Location 2025.xlsx",
                                 sheet_name = "SchoolLocations 2025",
                                 header = 0,
                                 dtype={"Location AGE ID": str,
                                        "Postcode": str})
ACARA_location_df.tail()

,Calendar Year,ACARA SML ID,Location AGE ID,School AGE ID,Rolled School ID,School Name,Suburb,State,Postcode,School Sector,...,Statistical Area 3,Statistical Area 3 Name,Statistical Area 4,Statistical Area 4 Name,Local Government Area,Local Government Area Name,State Electoral Division,State Electoral Division Name,Commonwealth Electoral Division,Commonwealth Electoral Division Name
11034,2025,53507,89688,25424.0,40771,QCHS - Cairns Campus,Edmonton,QLD,4869,Government,...,30602,Cairns - South,306,Cairns,32080,Cairns,30060,Mulgrave,317,Kennedy
11035,2025,53508,89636,28082.0,46387,Lighthouse Christian College Cranbourne - Sunn...,Red Cliffs,VIC,3496,Independent,...,21502,Mildura,215,North West,24780,Mildura,24904,Mildura (Northern Victoria),229,Mallee
11036,2025,53509,NaN,9268.0,45468,Oakwood School-Ormond Campus,Ormond,VIC,3204,Government,...,20802,Glen Eira,208,Melbourne - Inner South,22310,Glen Eira,21806,Caulfield (Southern Metropolitan),217,Goldstein
11037,2025,53510,NaN,87570.0,53288,SEDA College WA (Mount Claremont Campus),Mount Claremont,WA,6010,Independent,...,50301,Cottesloe - Claremont,503,Perth - Inner,56580,Nedlands,50018,Cottesloe,506,Curtin
11038,2025,53512,NaN,26753.0,40967,"Alta-1 College - Barker Road, Centennial Park",Centennial Park,WA,6330,Independent,...,50901,Albany,509,Western Australia - Wheat Belt,50080,Albany,50001,Albany,512,O'Connor

In [26]:
ACARA_location_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11039 entries, 0 to 11038
Data columns (total 31 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Calendar Year                         11039 non-null  int64
 1   ACARA SML ID                          11039 non-null  int64
 2   Location AGE ID                       10756 non-null  str
 3   School AGE ID                         10980 non-null  float64
 4   Rolled School ID                      11039 non-null  int64
 5   School Name                           11039 non-null  str
 6   Suburb                                11039 non-null  str
 7   State                                 11039 non-null  str
 8   Postcode                              11039 non-null  str
 9   School Sector                         11039 non-null  str
 10  School Type                           11039 non-null  str
 11  Special school                        11039 non-null  int64
 12  Campus Type                           11039 non-null  str
 13  Latitude                              11039 non-null  float64
 14  Longitude                             11039 non-null  float64
 15  ABS Remoteness Area                   11039 non-null  int64
 16  ABS Remoteness Area Name              11039 non-null  str
 17  Meshblock                             11039 non-null  int64
 18  Statistical Area 1                    11039 non-null  int64
 19  Statistical Area 2                    11039 non-null  int64
 20  Statistical Area 2 Name               11039 non-null  str
 21  Statistical Area 3                    11039 non-null  int64
 22  Statistical Area 3 Name               11039 non-null  str
 23  Statistical Area 4                    11039 non-null  int64
 24  Statistical Area 4 Name               11039 non-null  str
 25  Local Government Area                 11039 non-null  int64
 26  Local Government Area Name            11039 non-null  str
 27  State Electoral Division              11039 non-null  int64
 28  State Electoral Division Name         11039 non-null  str
 29  Commonwealth Electoral Division       11039 non-null  int64
 30  Commonwealth Electoral Division Name  11039 non-null  str
dtypes: float64(3), int64(13), str(15)
memory usage: 2.6 MB

In [21]:
#ACARA Profile
ACARA_profile_df = pd.read_excel("data/School Profile 2025.xlsx",
                                 sheet_name = "SchoolProfile 2025",
                                 header = 0,
                                 dtype={"Location AGE ID": str,
                                        "Postcode": str})
ACARA_profile_df.tail()

,Calendar Year,ACARA SML ID,Location AGE ID,School AGE ID,School Name,Suburb,State,Postcode,School Sector,School Type,...,Non-Teaching Staff,Full Time Equivalent Non-Teaching Staff,Total Enrolments,Girls Enrolments,Boys Enrolments,Full Time Equivalent Enrolments,Indigenous Enrolments (%),Language Background Other Than English - Yes (%),Language Background Other Than English - No (%),Language Background Other Than English - Not Stated (%)
9750,2025,53473,NaN,NaN,The Avenue School,Ferntree Gully,VIC,3156,Independent,Secondary,...,5.0,4.2,21.0,15.0,6.0,21.0,0.0,22.0,78.0,0.0
9751,2025,53477,NaN,NaN,Hubbard's School,Milton,QLD,4064,Independent,Secondary,...,3.0,2.4,58.0,38.0,20.0,54.4,0.0,8.0,92.0,0.0
9752,2025,53478,89600,88075.0,"Indie School, Logan",Browns Plains,QLD,4118,Independent,Secondary,...,134.0,37.9,586.0,356.0,230.0,586.0,18.0,8.0,92.0,0.0
9753,2025,53491,89497,89496.0,International Maarif Schools of Australia – Me...,Kilmore,VIC,3764,Independent,Primary,...,5.0,4.2,25.0,14.0,11.0,25.0,0.0,100.0,0.0,0.0
9754,2025,53492,89486,89485.0,Nawarddeken Academy Kunmayali School,West Arnhem Land,NT,0822,Independent,Secondary,...,19.0,5.3,34.0,13.0,21.0,34.0,100.0,100.0,0.0,0.0

In [22]:
ACARA_profile_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9755 entries, 0 to 9754
Data columns (total 35 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Calendar Year                                            9755 non-null   int64
 1   ACARA SML ID                                             9755 non-null   int64
 2   Location AGE ID                                          9739 non-null   str
 3   School AGE ID                                            9742 non-null   float64
 4   School Name                                              9755 non-null   str
 5   Suburb                                                   9755 non-null   str
 6   State                                                    9755 non-null   str
 7   Postcode                                                 9755 non-null   str
 8   School Sector                                            9755 non-null   str
 9   School Type                                              9755 non-null   str
 10  Campus Type                                              9755 non-null   str
 11  Rolled Reporting Description                             9755 non-null   str
 12  School URL                                               9748 non-null   str
 13  Governing Body                                           9747 non-null   str
 14  Governing Body URL                                       9747 non-null   str
 15  Year Range                                               9698 non-null   str
 16  Geolocation                                              9755 non-null   str
 17  ICSEA                                                    9623 non-null   float64
 18  ICSEA Percentile                                         9623 non-null   float64
 19  Bottom SEA Quarter (%)                                   9623 non-null   float64
 20  Lower Middle SEA Quarter (%)                             9623 non-null   float64
 21  Upper Middle SEA Quarter (%)                             9623 non-null   float64
 22  Top SEA Quarter (%)                                      9623 non-null   float64
 23  Teaching Staff                                           9749 non-null   float64
 24  Full Time Equivalent Teaching Staff                      9749 non-null   float64
 25  Non-Teaching Staff                                       9741 non-null   float64
 26  Full Time Equivalent Non-Teaching Staff                  9741 non-null   float64
 27  Total Enrolments                                         9698 non-null   float64
 28  Girls Enrolments                                         9696 non-null   float64
 29  Boys Enrolments                                          9691 non-null   float64
 30  Full Time Equivalent Enrolments                          9698 non-null   float64
 31  Indigenous Enrolments (%)                                9698 non-null   float64
 32  Language Background Other Than English - Yes (%)         9696 non-null   float64
 33  Language Background Other Than English - No (%)          9696 non-null   float64
 34  Language Background Other Than English - Not Stated (%)  9696 non-null   float64
dtypes: float64(19), int64(2), str(14)
memory usage: 2.6 MB

---

In [5]:
#TODO: inspect/clean
# descriptive statistics,

In [6]:
#TODO: merge

In [7]:
#TODO: select models /research question

In [8]:
# TODO: train/test split

In [9]:
#TODO: model train

In [10]:
#TODO: select evaluation metrics