<h1 style="text-align: center;">Individual Assignment 1 - Part 1</h1>
<h3 style="text-align: center;">Case Studies for Data Science - semester 2 2026</h3> 
<h4 style="text-align: center;"> Rose Munro s4054011 </h4>

In [3]:
#TODO: Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import sklearn TODO: select models

---

#### Load Australian Bureau of Statistics Data
##### Socio-Economic Indexes for Australia (SEIFA), 2021

In [ ]:
#TODO: load data sets (2)
#Read ABS SEIFA 2021 
SEIFA21_df = pd.read_excel("data/Postal Area, Indexes, SEIFA 2021.xlsx",
                         sheet_name = "Table 1",
                         header = 5,
                         dtype={"2021 Postal Area (POA) Code": str})#do not round postcodes, they are indexes not numric
SEIFA21_df.head()

,2021 Postal Area (POA) Code,Score,Decile,Score.1,Decile.1,Score.2,Decile.2,Score.3,Decile.3,Usual Resident Population,Data should be used with caution - area not well represented by SA1s,POA crosses state or territory boundaries
0,0800,1064.349794,9,1084.261433,9,921.395254,1,1089.647675,9.0,7149.0,NaN,NaN
1,0810,1026.802176,7,1036.266842,8,992.867218,5,1047.620794,8.0,34330.0,NaN,NaN
2,0812,981.137162,4,981.720979,6,977.777285,4,978.905626,6.0,18634.0,NaN,NaN
3,0820,1061.250806,9,1075.721877,9,981.896356,4,1076.326539,9.0,19920.0,NaN,NaN
4,0822,601.552207,1,760.604459,1,630.686758,1,885.789899,1.0,25304.0,NaN,NaN

In [ ]:
#rename cols ABS SEIFA
SEIFA21_df.columns = [
    "postcode",
    "irsd_score", #Index of Relative Socio-economic Disadvantage
    "irsd_decile",
    "irsad_score", # Index of Relative Socio-economic Advantage and Disadvantage	
    "irsad_decile",
    "ier_score", # Index of Economic Resources	
    "ier_decile",
    "ieo_score", # Index of Education and Occupation
    "ieo_decile",
    "population", # Usual Resident Population
    "caution_flag", # Data should be used with caution - area not well represented by SA1s
    "crosses_state_boundary" # POA crosses state or territory boundaries

]

SEIFA21_df.head(10)

,postcode,irsd_score,irsd_decile,irsad_score,irsad_decile,ier_score,ier_decile,ieo_score,ieo_decile,population,caution_flag,crosses_state_boundary
0,0800,1064.349794,9,1084.261433,9,921.395254,1,1089.647675,9.0,7149.0,NaN,NaN
1,0810,1026.802176,7,1036.266842,8,992.867218,5,1047.620794,8.0,34330.0,NaN,NaN
2,0812,981.137162,4,981.720979,6,977.777285,4,978.905626,6.0,18634.0,NaN,NaN
3,0820,1061.250806,9,1075.721877,9,981.896356,4,1076.326539,9.0,19920.0,NaN,NaN
4,0822,601.552207,1,760.604459,1,630.686758,1,885.789899,1.0,25304.0,NaN,NaN
5,0828,989.319795,5,999.91593,7,975.654307,4,985.144346,6.0,1697.0,NaN,NaN
6,0829,892.688966,1,857.561406,1,873.251436,1,841.989099,1.0,1963.0,NaN,NaN
7,0830,969.591287,4,963.341382,5,956.510726,3,948.909360,4.0,18501.0,NaN,NaN
8,0832,1048.448577,8,1032.478619,8,1025.31097,7,994.016467,7.0,18727.0,NaN,NaN
9,0834,1057.389015,9,1050.617815,8,1077.294216,9,983.332490,6.0,1811.0,NaN,NaN

In [12]:
print(SEIFA21_df.shape)
print(SEIFA21_df.columns)
SEIFA21_df.info()

(2629, 12)
Index(['postcode', 'irsd_score', 'irsd_decile', 'irsad_score', 'irsad_decile',
       'ier_score', 'ier_decile', 'ieo_score', 'ieo_decile', 'population',
       'caution_flag', 'crosses_state_boundary'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 2629 entries, 0 to 2628
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   postcode                2628 non-null   str
 1   irsd_score              2627 non-null   object
 2   irsd_decile             2627 non-null   object
 3   irsad_score             2627 non-null   object
 4   irsad_decile            2627 non-null   object
 5   ier_score               2627 non-null   object
 6   ier_decile              2627 non-null   object
 7   ieo_score               2627 non-null   float64
 8   ieo_decile              2627 non-null   float64
 9   population              2627 non-null   float64
 10  caution_flag            167 non-null    str
 11  crosses_state_boundary  15 non-null     str
dtypes: float64(3), object(6), str(3)
memory usage: 246.6+ KB

---

#### Load Australian Curriculum Assessment and Reporting Authority (ACARA) Data
##### School Profile & School Location, 2025

In [ ]:
#TODO: inspect/clean
# descriptive statistics,

In [ ]:
#TODO: merge

In [ ]:
#TODO: select models /research question

In [ ]:
# TODO: train/test split

In [ ]:
#TODO: model train

In [ ]:
#TODO: select evaluation metrics